on load:
    set {_wth} to netherite ingot named "&d凋零锭" with lore "&7散发着死亡的味道。" with nbt from "{CustomItem:WitheriteIngot}"
    set {_wth_h} to netherite leggings named "&d凋零护腿" with lore "&7终结。" with nbt from "{CustomItem:WitheriteLeggings}"
    enchant {_wth_h} with protection 7
    register smithing transform recipe:
        id: "custom:witherite_leggings"
        result: {_wth_h}
        template: netherite upgrade smithing template
        base: diamond sword
        addition: {_wth}
